/*
 * The Log in window. Takes a username and a password to log in to the 
 * system. 
 */
package mice_interactive;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author Oliver
 */
public class LogIn extends javax.swing.JFrame {

private InfDB infDB;
    
    public LogIn() {
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setBackground(Color.white);

        try
        {
            infDB = new InfDB("\\Users\\Oliver\\Documents\\Skola\\Mini_sup\\Realisering\\MICEDB.FDB");
            System.out.println("Uppkopplingen lyckades");
        }
        catch(InfException e)
                {
                    System.out.println(e.getMessage());
                }
        try
        {
            infDB = new InfDB("C:\\Users\\TP300LA-C4034\\Desktop\\Delkurs 4, Lill-supen\\InformatikDB\\MICEDB.FDB");
            System.out.println("Uppkopplingen lyckades");
        }
        catch(InfException e)
                {
                    System.out.println(e.getMessage());
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pfPassword = new javax.swing.JPasswordField();
        tfUsername = new javax.swing.JTextField();
        jlUsername = new javax.swing.JLabel();
        jlPassword = new javax.swing.JLabel();
        btnSignIn = new javax.swing.JButton();
        jlSignInLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 204));

        pfPassword.setText("Password");
        pfPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pfPasswordFocusGained(evt);
            }
        });
        pfPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pfPasswordMouseClicked(evt);
            }
        });
        pfPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pfPasswordKeyPressed(evt);
            }
        });

        tfUsername.setText("Username");
        tfUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfUsernameMouseClicked(evt);
            }
        });
        tfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameActionPerformed(evt);
            }
        });

        jlUsername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlUsername.setText("Username:");

        jlPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlPassword.setText("Password:");

        btnSignIn.setText("Sign in");
        btnSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignInMouseClicked(evt);
            }
        });

        jlSignInLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mice_interactive/MICE_SignIn_Logo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlSignInLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfUsername)
                                .addComponent(jlPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pfPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jlSignInLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jlPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfUsernameMouseClicked
        
        if(tfUsername.getText().equals("Username"))
        {
            tfUsername.setText("");
        }
        
    }//GEN-LAST:event_tfUsernameMouseClicked

    private void pfPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pfPasswordMouseClicked
        if(pfPassword.getText().equals("Password"))
        {
            pfPassword.setText("");
        }
    }//GEN-LAST:event_pfPasswordMouseClicked

    private void pfPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfPasswordFocusGained
        if(pfPassword.getText().equals("Password"))
        {
            pfPassword.setText("");
        }
    }//GEN-LAST:event_pfPasswordFocusGained

    private void tfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsernameActionPerformed

    private void btnSignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignInMouseClicked
        if(signIn())
        {
            setVisible(false);
            StartScreen startScreen = new StartScreen();
            startScreen.setVisible(true);
            
        }
        else
        {
            infoBox("Wrong password or username", "Error:");
            System.out.println("Felaktigt");
        }
    }//GEN-LAST:event_btnSignInMouseClicked

    private void pfPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfPasswordKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER)
       {
        if(signIn())
       {
            setVisible(false);
            StartScreen startScreen = new StartScreen();
            startScreen.setVisible(true); 
       }
           else
          {
            infoBox("Wrong password or username", "Error:");
            System.out.println("Felaktigt");
          }
       }
    }//GEN-LAST:event_pfPasswordKeyPressed
    
    private boolean signIn()
    {
        boolean valid = false;
        String sqlFraga = "SELECT administrator.Losenord from administrator "
                + "JOIN anstalld "
                + "ON administrator.aid = anstalld.aid "
                + "WHERE anstalld.anvnamn = " + "'" + tfUsername.getText() + "'";
                try
                {
                    String password = infDB.fetchSingle(sqlFraga);
                    if(pfPassword.getText().equals(password))
                    {
                       valid = true;
                    }
                }
                catch(InfException e)
                {
                    infoBox("Please try a Valid password and Username", "Error: Wrong password or username");
                    System.out.println(e.getMessage());
                }
                return valid;
    }
    
    private void infoBox(String infoMessage, String titleBar)
    {
        JOptionPane.showMessageDialog(null, infoMessage, titleBar, WIDTH);
    }
    
    public void fraga()
    {
                String sqlFraga = "SELECT administrator.Losenord from administrator "
                + "JOIN anstalld"
                + "ON administrator.aid = anstalld.aid"
                + "WHERE anstalld.anvnamn = " + "'" + tfUsername.getText() + "'";
               System.out.println(sqlFraga);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignIn;
    private javax.swing.JLabel jlPassword;
    private javax.swing.JLabel jlSignInLogo;
    private javax.swing.JLabel jlUsername;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
